version: "3.7"

services:
  app:
    image: nicolaswerner/menu-app
    ports:
      - "7000:7000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/menudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: menudb