version: 3.7

services:
  app:
    image: nicolaswerner/menu-app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - ./postgres-data:/var/lib/posrgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres